In [2]:
#Dependencies
import pandas as pd

In [9]:
#read in data
permits_df = pd.read_csv("../data/sidewalk-cafe-permits.csv")
#drop duplicates but there are none
permits_df.drop_duplicates()
permits_df.head()

,PERMIT NUMBER,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ISSUED DATE,EXPIRATION DATE,PAYMENT DATE,ADDRESS,ADDRESS NUMBER START,...,WARD PRECINCT,POLICE DISTRICT,LATITUDE,LONGITUDE,LOCATION,Community Areas,Zip Codes,Boundaries - ZIP Codes,Census Tracts,Wards
0,1142666,458934,1,"TINTO & TAPAS, LLC",TINTO & TAPAS,2019-11-25T00:00:00.000,2020-02-29T00:00:00.000,2019-10-29T00:00:00.000,7958 W BELMONT AVE,7958,...,38-30,16.0,41.937859,-87.826255,"{'latitude': '41.937859427847215', 'human_addr...",17.0,22254.0,52.0,457.0,19.0
1,1142290,294900,4,"PIE CAFE, LLC",Pie cafe,2019-10-15T00:00:00.000,2020-02-29T00:00:00.000,2019-10-15T00:00:00.000,5357 N ASHLAND AVE,5357,...,40-26,20.0,41.979717,-87.669565,"{'latitude': '41.979717096739535', 'human_addr...",76.0,22616.0,15.0,564.0,24.0
2,1142132,459163,1,KALIFLOWER 333 NORTH MICHIGAN AVE LLC,KALIFLOWER,2019-09-20T00:00:00.000,2020-02-29T00:00:00.000,2019-09-20T00:00:00.000,333 N MICHIGAN AVE,333,...,42-40,1.0,41.887543,-87.624407,"{'latitude': '41.88754294139151', 'human_addre...",38.0,14309.0,42.0,580.0,36.0
3,1142101,384478,1,1732 N MILWAUKEE RESTAURANT LLC,SMALL CHEVAL,2019-09-20T00:00:00.000,2020-02-29T00:00:00.000,2019-09-20T00:00:00.000,1732 N MILWAUKEE AVE,1732,...,32-6,14.0,41.912730,-87.681327,"{'latitude': '41.91273041812944', 'human_addre...",25.0,22535.0,1.0,298.0,40.0
4,1142100,456144,1,"THE WHALE CHICAGO, LLC",THE WHALE CHICAGO,2019-09-19T00:00:00.000,2020-02-29T00:00:00.000,2019-09-19T00:00:00.000,2427-2431 N MILWAUKEE AVE,2427,...,1-19,14.0,41.925388,-87.701170,"{'latitude': '41.92538801822599', 'human_addre...",23.0,22535.0,1.0,548.0,41.0

In [13]:
permits_df.sort_values("ISSUED DATE", ascending=True).head(15)

,PERMIT NUMBER,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ISSUED DATE,EXPIRATION DATE,PAYMENT DATE,ADDRESS,ADDRESS NUMBER START,...,WARD PRECINCT,POLICE DISTRICT,LATITUDE,LONGITUDE,LOCATION,Community Areas,Zip Codes,Boundaries - ZIP Codes,Census Tracts,Wards
17983,1007419,10393,1,"BERNIE'S, INC.","BERNIE'S, INC.",2001-03-14T00:00:00.000,2001-11-01T00:00:00.000,2001-03-14T00:00:00.000,3664 N CLARK ST,3664,...,44-50,19.0,41.948844,-87.658009,"{'latitude': '41.948843780887984', 'human_addr...",57.0,21186.0,53.0,691.0,25.0
17985,1007416,16079,1,"PIPE DREAM, INC.",DELEECE,2001-03-15T00:00:00.000,2001-11-01T00:00:00.000,2001-03-15T00:00:00.000,4004 N SOUTHPORT AVE,4004,...,47-24,19.0,41.954527,-87.664365,"{'latitude': '41.954527147910014', 'human_addr...",57.0,21186.0,53.0,650.0,18.0
17987,1007411,12,1,"ZEPHYR ICE CREAM SHOP, INC.",ZEPHYR ICE CREAM SHOP,2001-03-19T00:00:00.000,2001-11-01T00:00:00.000,2001-03-16T00:00:00.000,1767 W WILSON AVE,1767,...,47-5,19.0,41.965067,-87.673582,"{'latitude': '41.965067484862175', 'human_addr...",31.0,22616.0,15.0,576.0,18.0
17984,1007417,16296,1,GUSTO MEXICANO INC,EL CID TACOS #2,2001-03-20T00:00:00.000,2001-11-01T00:00:00.000,2001-03-20T00:00:00.000,2645 N KEDZIE AVE,2645,...,32-7,14.0,41.929763,-87.707223,"{'latitude': '41.92976286483289', 'human_addre...",23.0,22535.0,1.0,549.0,40.0
17988,1007406,315,1,D AND J PIZZA INC.,RANALLI'S ON LINCOLN,2001-03-20T00:00:00.000,2001-11-01T00:00:00.000,2001-03-20T00:00:00.000,1925 N LINCOLN AVE,1925,...,43-37,18.0,41.917217,-87.637044,"{'latitude': '41.91721711853109', 'human_addre...",68.0,21190.0,16.0,271.0,34.0
17968,1007695,85572,2,"JOHN B. 2, INC.",JOHN BARLEYCORN MEMORIAL PUB,2001-03-22T00:00:00.000,2001-11-01T00:00:00.000,2001-03-22T00:00:00.000,658 W BELDEN AVE,658,...,43-35,18.0,41.923779,-87.646157,"{'latitude': '41.92377936102007', 'human_addre...",68.0,21190.0,16.0,798.0,34.0
17908,1008298,21820,1,"BRANTIN, INC.",CAFE LUCIANO,2001-03-22T00:00:00.000,2001-11-01T00:00:00.000,2001-03-22T00:00:00.000,871 N RUSH ST,871,...,42-61,18.0,41.898711,-87.626387,"{'latitude': '41.89871051609227', 'human_addre...",37.0,21182.0,6.0,104.0,36.0
17909,1008297,207993,11,ABP CORPORATION,AU BON PAIN,2001-03-22T00:00:00.000,2001-11-01T00:00:00.000,2001-03-22T00:00:00.000,122 S MICHIGAN AVE,122,...,42-9,1.0,41.880263,-87.624505,"{'latitude': '41.88026337218459', 'human_addre...",38.0,14311.0,34.0,367.0,36.0
17911,1008288,207993,10,ABP CORPORATION,AU BON PAIN,2001-03-22T00:00:00.000,2001-11-01T00:00:00.000,2001-03-22T00:00:00.000,33 N DEARBORN ST,33,...,42-9,1.0,41.882806,-87.629281,"{'latitude': '41.88280622661767', 'human_addre...",38.0,14310.0,41.0,92.0,36.0
17952,1008084,14172,1,"LIZZIE MCNEILL'S, INC.",LIZZIE MC NEILLS,2001-03-22T00:00:00.000,2001-11-01T00:00:00.000,2001-03-22T00:00:00.000,400 N MCCLURG CT,400,...,42-54,18.0,41.889118,-87.617755,"{'latitude': '41.88911847301037', 'human_addre...",37.0,21182.0,6.0,159.0,36.0
17912,1008284,4346,1,WINDY CITY FRUIT & NUT CO,WINDY CITY SWEETS,2001-03-22T00:00:00.000,2001-11-01T00:00:00.000,2001-03-22T00:00:00.000,3308 N BROADWAY,3308,...,44-37,19.0,41.942208,-87.644614,"{'latitude': '41.94220819722684', 'human_addre...",57.0,4449.0,22.0,730.0,25.0
17972,1007673,15895,1,"UCM, INC.",J. T. COLLINS PUB,2001-03-22T00:00:00.000,2001-11-01T00:00:00.000,2001-03-21T00:00:00.000,3358 N PAULINA ST,3358,...,47-38,19.0,41.943261,-87.671339,"{'latitude': '41.94326094798753', 'human_addre...",57.0,4449.0,22.0,742.0,18.0
17941,1008160,18563,1,VOLARE ASSOCIATES LIMITED. PARTNER,VOLARE,2001-03-22T00:00:00.000,2001-11-01T00:00:00.000,2001-03-22T00:00:00.000,201 E GRAND AVE,201,...,42-41,18.0,41.891652,-87.622604,"{'latitude': '41.89165221441017', 'human_addre...",37.0,21182.0,6.0,159.0,36.0
17938,1008171,16085,1,"FOREGIVENESS, INC.",HUNT CLUB,2001-03-22T00:00:00.000,2001-11-01T00:00:00.000,2001-03-21T00:00:00.000,1100 N STATE ST,1100,...,2-60,18.0,41.901906,-87.628493,"{'latitude': '41.90190555423841', 'human_addre...",37.0,14926.0,54.0,230.0,11.0
17887,1008460,19874,1,RAYHOON INC,BASIL LEAF CAFE,2001-03-22T00:00:00.000,2001-11-01T00:00:00.000,2001-03-22T00:00:00.000,2460 N CLARK ST,2460,...,43-34,19.0,41.927067,-87.641530,"{'latitude': '41.92706675470967', 'human_addre...",68.0,21190.0,16.0,185.0,34.0